# Generated by Django 3.1 on 2020-08-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
